import type { TValidatorPlugin } from "@atscript/typescript/utils";
import type { DbValidationContext } from "@atscript/db";
import { ObjectId } from "mongodb";

export const validateMongoIdPlugin: TValidatorPlugin = (ctx, def, value) => {
  if ((def.type.tags as Set<string>)?.has("objectId")) {
    // ObjectId _id is auto-generated by MongoDB — optional on insert/replace.
    // Only applies to _id; other objectId fields (e.g. FK references) remain required.
    if (ctx.path === "_id" && (value === undefined || value === null)) {
      const dbCtx = ctx.context as DbValidationContext | undefined;
      if (dbCtx && (dbCtx.mode === "insert" || dbCtx.mode === "replace")) {
        return true;
      }
    }
    return ctx.validateAnnotatedType(def, value instanceof ObjectId ? value.toString() : value);
  }
};
