/* oxlint-disable */
/* eslint-disable */
/**
 * 🪄 This file was generated by Atscript (@atscript/db model manifest)
 * Do not edit this file!
 *
 * Re-generate with `npx asc -f dts`.
 */
import { MfEvent } from "./events.as"
import { MfActiveUser } from "./users.as"
import { MfUser } from "./users.as"

export const dbTables = [MfEvent, MfUser] as const
export const dbViews = [MfActiveUser] as const
/** Every @db.table / @db.view model in this project. */
export const atscriptModels = [MfEvent, MfActiveUser, MfUser] as const
/** Models grouped by @db.space (absent annotation → "default"). */
export const modelsBySpace = {
  "default": [MfActiveUser, MfUser] as const,
  "analytics": [MfEvent] as const,
} as const
