packages:
  - packages/*
  - docs

catalog:
  "@atscript/core": ^0.1.81
  "@atscript/typescript": ^0.1.81
  "@moostjs/event-http": ^0.6.29
  "@types/node": ^24
  "@uniqu/core": ^0.1.7
  "@uniqu/url": ^0.1.7
  "@wooksjs/event-core": ^0.7.19
  "@wooksjs/event-http": ^0.7.19
  "@wooksjs/http-body": ^0.7.19
  moost: ^0.6.29
  sqlite-vec: ^0.1.9
  typescript: ^5
  unplugin-atscript: ^0.1.81
  vite: npm:@voidzero-dev/vite-plus-core@0.1.12
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
  ignoreMissing:
    - "@prostojs/logger"
    - "@prostojs/router"
