packages:
  - packages/*
  - docs

catalog:
  "@atscript/core": ^0.1.48
  "@atscript/typescript": ^0.1.48
  "@types/node": ^24
  "@moostjs/event-http": ^0.6.7
  moost: ^0.6.7
  "@uniqu/core": ^0.1.4
  "@uniqu/url": ^0.1.4
  unplugin-atscript: ^0.1.48
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.1.12
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
  ignoreMissing:
    - "@prostojs/logger"
    - "@prostojs/router"
