import { describe, it, expect, beforeAll } from "vite-plus/test";
import { DbSpace } from "@atscript/db";
import { PostgresAdapter } from "../postgres-adapter";
import { prepareFixtures, createMockDriver } from "./test-utils";

beforeAll(async () => {
  await prepareFixtures();
});

describe("PostgresAdapter", () => {
  describe("ensureTable (CREATE TABLE)", () => {
    it("emits correct DDL for basic table", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      await table.ensureTable();

      const createCall = driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"));
      expect(createCall).toBeDefined();
      const sql = createCall!.sql;

      // Double-quote identifiers
      expect(sql).toContain('"id"');
      expect(sql).toContain('"email_address"');
      expect(sql).toContain('"name"');

      // BIGINT for @db.default.now number field (epoch ms, not TIMESTAMPTZ)
      expect(sql).toContain("BIGINT");
      expect(sql).toContain("extract(epoch from now())");

      // No MySQL-specific syntax
      expect(sql).not.toContain("ENGINE");
      expect(sql).not.toContain("CHARSET");
      expect(sql).not.toContain("utf8mb4");
      expect(sql).not.toContain("AUTO_INCREMENT");
    });

    it("uses GENERATED BY DEFAULT AS IDENTITY for increment", async () => {
      const { ProfileTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(ProfileTable as any);
      await table.ensureTable();

      const sql = driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"))!.sql;
      expect(sql).toContain("GENERATED BY DEFAULT AS IDENTITY");
    });

    it("uses gen_random_uuid() for uuid default", async () => {
      const { TokenTable } = await import("./fixtures/default-fns.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(TokenTable as any);
      await table.ensureTable();

      const sql = driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"))!.sql;
      expect(sql).toContain("gen_random_uuid()");
    });

    it("uses GENERATED AS IDENTITY with START WITH for increment start value", async () => {
      const { CounterTable } = await import("./fixtures/default-fns.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(CounterTable as any);
      await table.ensureTable();

      const sql = driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"))!.sql;
      expect(sql).toContain("GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
    });

    it("uses BOOLEAN for boolean fields (not TINYINT)", async () => {
      const { ProfileTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(ProfileTable as any);
      await table.ensureTable();

      const sql = driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"))!.sql;
      expect(sql).toContain("BOOLEAN");
      expect(sql).not.toContain("TINYINT");
    });

    it("uses JSONB for json/object/array fields", async () => {
      const { ProfileTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(ProfileTable as any);
      await table.ensureTable();

      const sql = driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"))!.sql;
      expect(sql).toContain("JSONB");
    });
  });

  describe("vector support", () => {
    it("uses vector(N) column type when pgvector is available", async () => {
      const { ArticlesTable } = await import("./fixtures/vector-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(ArticlesTable as any);
      await table.ensureTable();

      const createCall = driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"));
      expect(createCall).toBeDefined();
      expect(createCall!.sql).toContain("vector(1536)");
      expect(createCall!.sql).not.toMatch(/"embedding" JSONB/);
    });

    it("converts number[] to pgvector string on insert (toStorage)", async () => {
      const { ArticlesTable } = await import("./fixtures/vector-table.as");
      const driver = createMockDriver({ runResult: { rows: [{ id: "x" }] } });
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(ArticlesTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      await table.insertOne({ id: "x", title: "Test", embedding: [0.1, 0.2, 0.3] });

      const insertCall = driver.calls.find((c) => c.sql.includes("INSERT"));
      expect(insertCall).toBeDefined();
      // Vector should be serialized as pgvector string, not a JS array
      const embeddingParam = insertCall!.params!.find(
        (p) => typeof p === "string" && p.startsWith("["),
      );
      expect(embeddingParam).toBe("[0.1,0.2,0.3]");
    });

    it("converts pgvector string back to number[] on read (fromStorage)", async () => {
      const { ArticlesTable } = await import("./fixtures/vector-table.as");
      const driver = createMockDriver({
        allResult: [{ id: "x", title: "Test", embedding: "[0.1,0.2,0.3]" }],
      });
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(ArticlesTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const rows = await table.findMany({});
      expect(rows).toHaveLength(1);
      expect((rows[0] as Record<string, unknown>).embedding).toEqual([0.1, 0.2, 0.3]);
    });
  });

  describe("nocase collation (CITEXT)", () => {
    it("uses CITEXT type for nocase columns in CREATE TABLE", async () => {
      const { AccountTable } = await import("./fixtures/collate.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(AccountTable as any);
      await table.ensureTable();

      // Should provision citext extension
      const extCall = driver.calls.find((c) => c.sql.includes("citext"));
      expect(extCall).toBeDefined();

      // nickname column should be CITEXT (not TEXT)
      const createCall = driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"));
      expect(createCall).toBeDefined();
      expect(createCall!.sql).toContain("CITEXT");
      // email should NOT be CITEXT
      expect(createCall!.sql).toMatch(/"email" TEXT/);
    });

    it("queries nocase columns without LOWER wrapping (CITEXT handles it)", async () => {
      const { AccountTable } = await import("./fixtures/collate.as");
      const driver = createMockDriver({ getResult: { id: 1, nickname: "AlIcE", email: "a@b.c" } });
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(AccountTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.findOne({ filter: { nickname: "AlIcE" }, controls: {} });

      const selectCall = driver.calls.find((c) => c.sql.includes("SELECT"));
      expect(selectCall).toBeDefined();
      // No LOWER wrapping — CITEXT type handles case-insensitivity at storage level
      expect(selectCall!.sql).not.toContain("LOWER");
      // Value preserves original case (CITEXT comparison is case-insensitive)
      expect(selectCall!.params).toContain("AlIcE");
    });

    it("provisions citext extension in syncColumns before ALTER TABLE", async () => {
      const { AccountTable } = await import("./fixtures/collate.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(AccountTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.syncColumns({
        added: table.fieldDescriptors.filter((f) => f.physicalName === "nickname"),
        removed: [],
        renamed: [],
        typeChanged: [],
        nullableChanged: [],
        defaultChanged: [],
        conflicts: [],
      });

      // citext extension should be created BEFORE the ALTER TABLE ADD COLUMN
      const extIdx = driver.calls.findIndex((c) => c.sql.includes("citext"));
      const alterIdx = driver.calls.findIndex((c) => c.sql.includes("ALTER TABLE"));
      expect(extIdx).toBeGreaterThanOrEqual(0);
      expect(alterIdx).toBeGreaterThan(extIdx);
    });
  });

  describe("composite key operations", () => {
    it("updateOne generates correct SQL for composite-key filter", async () => {
      const { Task } = await import("./fixtures/fk-tables.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(Task as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.updateOne({ id: 1, projectId: 2 }, { title: "Updated" });

      const updateCall = driver.calls.find((c) => c.sql.includes("UPDATE"));
      expect(updateCall).toBeDefined();
      const sql = updateCall!.sql;

      // SET uses $1
      expect(sql).toMatch(/"title" = \$1/);
      // WHERE uses $2 and $3 (offset by 1 SET param)
      expect(sql).toMatch(/\$2/);
      expect(sql).toMatch(/\$3/);
      // ctid subquery
      expect(sql).toContain("ctid");
      // No ? placeholders
      expect(sql).not.toContain("?");
      // Params: [setValue, filterVal1, filterVal2]
      expect(updateCall!.params).toEqual(["Updated", 1, 2]);
    });

    it("deleteOne generates correct SQL for composite-key filter", async () => {
      const { Task } = await import("./fixtures/fk-tables.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(Task as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.deleteOne({ id: 1, projectId: 2 });

      const deleteCall = driver.calls.find((c) => c.sql.includes("DELETE"));
      expect(deleteCall).toBeDefined();
      expect(deleteCall!.sql).toContain("ctid");
      expect(deleteCall!.sql).toMatch(/\$1/);
      expect(deleteCall!.sql).toMatch(/\$2/);
      expect(deleteCall!.sql).not.toContain("?");
    });
  });

  describe("insertMany batching", () => {
    it("uses multi-row INSERT with $N placeholders", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver({ runResult: { rows: [{ id: 1 }, { id: 2 }, { id: 3 }] } });
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.insertMany([
        { id: 1, name: "Alice", email_address: "a@test.com" },
        { id: 2, name: "Bob", email_address: "b@test.com" },
        { id: 3, name: "Charlie", email_address: "c@test.com" },
      ]);

      // Should be a single INSERT with VALUES (...), (...), (...)
      const insertCalls = driver.calls.filter((c) => c.sql.includes("INSERT"));
      expect(insertCalls).toHaveLength(1);
      const sql = insertCalls[0].sql;
      // 3 rows x 3 columns = 9 params
      expect(sql).toContain("$1");
      expect(sql).toContain("$9");
      expect(sql).toContain("RETURNING");
      expect(sql).not.toContain("?");
    });
  });

  describe("CRUD operations (adapter-level)", () => {
    // Test adapter methods directly to avoid table-layer data processing complexity
    it("insertOne uses RETURNING clause and $N placeholders", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver({ runResult: { rows: [{ id: 42 }] } });
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      // Call adapter directly
      const adapter = (table as any).adapter as PostgresAdapter;
      const result = await adapter.insertOne({
        id: 1,
        name: "Alice",
        email_address: "alice@test.com",
      });

      const insertCall = driver.calls.find((c) => c.sql.includes("INSERT"));
      expect(insertCall).toBeDefined();
      expect(insertCall!.sql).toContain("RETURNING");
      expect(insertCall!.sql).toMatch(/\$\d/);
      expect(insertCall!.sql).not.toContain("?");
      expect(result.insertedId).toBe(1);
    });

    it("findOne uses $N placeholders", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver({ getResult: { id: 1, name: "Alice" } });
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.findOne({ filter: { name: "Alice" }, controls: {} });

      const selectCall = driver.calls.find((c) => c.sql.includes("SELECT"));
      expect(selectCall).toBeDefined();
      expect(selectCall!.sql).toMatch(/\$1/);
      expect(selectCall!.sql).not.toContain("?");
    });

    it("updateOne uses ctid subquery (no LIMIT on UPDATE)", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.updateOne({ id: 1 }, { name: "Bob" });

      const updateCall = driver.calls.find((c) => c.sql.includes("UPDATE"));
      expect(updateCall).toBeDefined();
      expect(updateCall!.sql).toContain("ctid");
      expect(updateCall!.sql).toContain("LIMIT 1");
      expect(updateCall!.sql).toMatch(/\$\d/);
      expect(updateCall!.sql).not.toContain("?");
    });

    it("deleteOne uses ctid subquery", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.deleteOne({ id: 1 });

      const deleteCall = driver.calls.find((c) => c.sql.includes("DELETE"));
      expect(deleteCall).toBeDefined();
      expect(deleteCall!.sql).toContain("ctid");
      expect(deleteCall!.sql).toContain("LIMIT 1");
      expect(deleteCall!.sql).toMatch(/\$\d/);
      expect(deleteCall!.sql).not.toContain("?");
    });

    it("deleteMany uses $N placeholders without ctid", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.deleteMany({ name: "old" });

      const deleteCall = driver.calls.find((c) => c.sql.includes("DELETE"));
      expect(deleteCall).toBeDefined();
      expect(deleteCall!.sql).not.toContain("ctid");
      expect(deleteCall!.sql).toMatch(/\$\d/);
    });
  });

  describe("FK support", () => {
    it("creates FK constraints in CREATE TABLE", async () => {
      const { Task } = await import("./fixtures/fk-tables.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(Task as any);
      await table.ensureTable();

      const sql = driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"))!.sql;
      expect(sql).toContain("FOREIGN KEY");
      expect(sql).toContain("REFERENCES");
    });
  });

  describe("error mapping", () => {
    it("maps 23505 to CONFLICT", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      await table.ensureTable();

      // Override run AFTER ensureTable so DDL calls succeed
      driver.run = async () => {
        throw Object.assign(new Error("unique_violation"), {
          code: "23505",
          detail: "Key (email_address)=(a@b.c) already exists.",
          constraint: "users_email_address_key",
        });
      };

      const adapter = (table as any).adapter as PostgresAdapter;
      await expect(
        adapter.insertOne({ id: 1, name: "X", email_address: "a@b.c" }),
      ).rejects.toMatchObject({
        code: "CONFLICT",
      });
    });

    it("maps 23503 to FK_VIOLATION", async () => {
      const { Task } = await import("./fixtures/fk-tables.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(Task as any);
      await table.ensureTable();

      driver.run = async () => {
        throw Object.assign(new Error("fk_violation"), {
          code: "23503",
          detail: 'Key (projectId)=(999) is not present in table "projects".',
          constraint: "tasks_projectid_fkey",
        });
      };

      const adapter = (table as any).adapter as PostgresAdapter;
      await expect(adapter.insertOne({ id: 1, title: "X", projectId: 999 })).rejects.toMatchObject({
        code: "FK_VIOLATION",
      });
    });
  });

  describe("afterSyncTable (identity sequence reset)", () => {
    it("resets identity sequence via setval after sync", async () => {
      const { ProfileTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver({ runResult: { rows: [{ setval: 2 }] } });
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(ProfileTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.afterSyncTable();

      const setvalCall = driver.calls.find((c) => c.sql.includes("setval"));
      expect(setvalCall).toBeDefined();
      expect(setvalCall!.sql).toContain("pg_get_serial_sequence");
      expect(setvalCall!.sql).toContain("'id'");
      // Uses is_called=false when table is empty (MAX is NULL)
      expect(setvalCall!.sql).toContain("IS NOT NULL");
    });

    it("uses configured start value as empty-table fallback", async () => {
      const { CounterTable } = await import("./fixtures/default-fns.as");
      const driver = createMockDriver({ runResult: { rows: [{ setval: 1000 }] } });
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(CounterTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.afterSyncTable();

      const setvalCall = driver.calls.find((c) => c.sql.includes("setval"));
      expect(setvalCall).toBeDefined();
      // Empty table fallback should be 1000 (from @db.default.increment 1000), not 1
      expect(setvalCall!.sql).toContain('COALESCE(MAX("id"), 1000)');
    });

    it("skips sequence reset when no increment fields", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      await table.ensureTable();
      driver.calls.length = 0;

      const adapter = (table as any).adapter as PostgresAdapter;
      await adapter.afterSyncTable();

      const setvalCall = driver.calls.find((c) => c.sql.includes("setval"));
      expect(setvalCall).toBeUndefined();
    });
  });

  describe("capabilities", () => {
    it("supportsNativeForeignKeys", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      expect((table as any).adapter.supportsNativeForeignKeys()).toBe(true);
    });

    it("supportsNativeValueDefaults", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      expect((table as any).adapter.supportsNativeValueDefaults()).toBe(true);
    });

    it("includes uuid in nativeDefaultFns", async () => {
      const { UsersTable } = await import("./fixtures/test-table.as");
      const driver = createMockDriver();
      const space = new DbSpace(() => new PostgresAdapter(driver));
      const table = space.getTable(UsersTable as any);
      const fns = (table as any).adapter.nativeDefaultFns();
      expect(fns.has("uuid")).toBe(true);
      expect(fns.has("now")).toBe(true);
      expect(fns.has("increment")).toBe(true);
    });
  });
});
