import { describe, it, expect, beforeAll } from "vite-plus/test";
import { AtscriptDbTable, AtscriptDbView, DbSpace } from "@atscript/db";
import type { TColumnDiff, TDbFieldMeta } from "@atscript/db";

import { PostgresAdapter } from "../postgres-adapter";
import { prepareFixtures, createMockDriver } from "./test-utils";

let fx: Record<string, any>;
let CycleA: any;

function diff(partial: Partial<TColumnDiff>): TColumnDiff {
  return {
    added: [],
    removed: [],
    renamed: [],
    typeChanged: [],
    nullableChanged: [],
    defaultChanged: [],
    conflicts: [],
    ...partial,
  };
}

function pick(table: any, path: string): TDbFieldMeta {
  const f = table.fieldDescriptors.find((d: TDbFieldMeta) => d.path === path);
  if (!f) throw new Error(`no field ${path}`);
  return f;
}

beforeAll(async () => {
  await prepareFixtures();
  fx = await import("./fixtures/sync-preflight.as");
  CycleA = (await import("./fixtures/pf-cycle-a.as")).PfCycleA;
});

// Recorded-DDL coverage for the schema-sync primitives (since 0.1.128).
describe("PostgresAdapter — schema sync primitives", () => {
  it("rebuildPrimaryKey: DROP CONSTRAINT + ADD PRIMARY KEY in one statement", async () => {
    const driver = createMockDriver({ getResult: { conname: "pf_tokens_pkey" } });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfTokenV2, adapter);
    await adapter.rebuildPrimaryKey({ from: ["id"], to: ["code"] });
    const alter = driver.calls.filter((c) => c.method === "exec");
    expect(alter).toHaveLength(1);
    expect(alter[0].sql).toBe(
      'ALTER TABLE "pf_tokens" DROP CONSTRAINT "pf_tokens_pkey", ADD PRIMARY KEY ("code")',
    );
    expect(driver.calls[0].sql).toContain("contype = 'p'");
  });

  it("rebuildPrimaryKey: composite key, and a first key without DROP", async () => {
    const driver = createMockDriver({ getResult: null });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfTokenV2, adapter);
    await adapter.rebuildPrimaryKey({ from: [], to: ["code", "label"] });
    expect(driver.calls.find((c) => c.method === "exec")!.sql).toBe(
      'ALTER TABLE "pf_tokens" ADD PRIMARY KEY ("code", "label")',
    );
  });

  it("identity: a demoted increment column gets DROP IDENTITY, never DROP DEFAULT or increment()", async () => {
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    const table = new AtscriptDbTable(fx.PfTokenV2, adapter);
    await adapter.syncColumns(
      diff({ defaultChanged: [{ field: pick(table, "id"), oldDefault: "fn:increment" }] }),
    );
    const ddl = driver.calls.filter((c) => c.method === "exec").map((c) => c.sql);
    expect(ddl).toEqual(['ALTER TABLE "pf_tokens" ALTER COLUMN "id" DROP IDENTITY IF EXISTS']);
  });

  it("identity: gaining @db.default.increment emits ADD GENERATED (dropping a prior default first)", async () => {
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    const table = new AtscriptDbTable(fx.PfTokenV1, adapter);
    await adapter.syncColumns(
      diff({
        defaultChanged: [{ field: pick(table, "id"), oldDefault: "0", newDefault: "fn:increment" }],
      }),
    );
    const ddl = driver.calls.filter((c) => c.method === "exec").map((c) => c.sql);
    expect(ddl).toEqual([
      'ALTER TABLE "pf_tokens" ALTER COLUMN "id" DROP DEFAULT',
      'ALTER TABLE "pf_tokens" ALTER COLUMN "id" SET NOT NULL',
      'ALTER TABLE "pf_tokens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY',
    ]);
    expect(ddl.join("\n")).not.toContain("increment()");
  });

  it("identity → value default: DROP IDENTITY then SET DEFAULT", async () => {
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    const table = new AtscriptDbTable(fx.PfTokenV2, adapter);
    const id = {
      ...pick(table, "id"),
      defaultValue: { kind: "value", value: "7" },
    } as TDbFieldMeta;
    await adapter.syncColumns(
      diff({ defaultChanged: [{ field: id, oldDefault: "fn:increment", newDefault: "7" }] }),
    );
    expect(driver.calls.filter((c) => c.method === "exec").map((c) => c.sql)).toEqual([
      'ALTER TABLE "pf_tokens" ALTER COLUMN "id" DROP IDENTITY IF EXISTS',
      'ALTER TABLE "pf_tokens" ALTER COLUMN "id" SET DEFAULT 7',
    ]);
  });

  it("sync-owned drops never CASCADE; a cycle is one multi-table DROP", async () => {
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfParent, adapter);
    await adapter.dropTable();
    await adapter.dropTableByName("pf_children");
    await adapter.dropTablesByName(["pf_cycle_a", "pf_cycle_b"]);
    const ddl = driver.calls.filter((c) => c.method === "exec").map((c) => c.sql);
    expect(ddl).toEqual([
      'DROP TABLE IF EXISTS "pf_parents"',
      'DROP TABLE IF EXISTS "pf_children"',
      'DROP TABLE IF EXISTS "pf_cycle_a", "pf_cycle_b"',
    ]);
    expect(ddl.join("\n")).not.toContain("CASCADE");
  });

  it("hasRows uses SELECT EXISTS on the own or a named table", async () => {
    const driver = createMockDriver({ getResult: { present: true } });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfTokenV1, adapter);
    expect(await adapter.hasRows()).toBe(true);
    expect(driver.calls[0].sql).toBe('SELECT EXISTS (SELECT 1 FROM "pf_tokens") AS "present"');
    await adapter.hasRows("old_tokens");
    expect(driver.calls[1].sql).toBe('SELECT EXISTS (SELECT 1 FROM "old_tokens") AS "present"');
  });

  it("getReferencingForeignKeys queries pg_constraint by referenced relation", async () => {
    const driver = createMockDriver({
      allResult: [
        {
          table_name: "children",
          constraint_name: "fk1",
          columns: ["pa", "pb"],
          ref_columns: ["a", "b"],
        },
        { table_name: "logs", constraint_name: "fk2", columns: ["parentId"], ref_columns: ["id"] },
      ],
    });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfParent, adapter);
    expect(await adapter.getReferencingForeignKeys("pf_parents")).toEqual([
      { table: "children", fields: ["pa", "pb"], targetFields: ["a", "b"] },
      { table: "logs", fields: ["parentId"], targetFields: ["id"] },
    ]);
    const sql = driver.calls[0].sql;
    expect(sql).toContain("pg_constraint");
    expect(sql).toContain("c.contype = 'f'");
    expect(sql).toContain("confrelid");
    expect(driver.calls[0].params?.[0]).toBe("pf_parents");
  });

  it("getObjectKind maps pg_class.relkind", async () => {
    for (const [relkind, kind] of [
      ["r", "table"],
      ["p", "table"],
      ["v", "view"],
      ["m", "materialized"],
    ] as const) {
      const driver = createMockDriver({ getResult: { relkind } });
      const adapter = new PostgresAdapter(driver);
      new AtscriptDbTable(fx.PfParent, adapter);
      expect(await adapter.getObjectKind("x")).toBe(kind);
    }
    const driver = createMockDriver({ getResult: null });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfParent, adapter);
    expect(await adapter.getObjectKind("x")).toBeUndefined();
  });

  it("ensureTable omits inline FKs to deferred cycle members", async () => {
    const driver = createMockDriver();
    const space = new DbSpace(() => new PostgresAdapter(driver));
    const adapter = space.getAdapter(CycleA);
    await adapter.ensureTable({ deferForeignKeysTo: new Set(["pf_cycle_a", "pf_cycle_b"]) });
    expect(driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"))!.sql).not.toContain(
      "FOREIGN KEY",
    );
    driver.calls.length = 0;
    await adapter.ensureTable();
    expect(driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"))!.sql).toContain(
      'FOREIGN KEY ("bId") REFERENCES "pf_cycle_b" ("id")',
    );
  });

  it("creates a view for a duck-typed readable (structural isView) and excludes @db.ignore fields", async () => {
    const real = new DbSpace(() => new PostgresAdapter(createMockDriver())).getView(
      fx.PfTokenList,
    ) as AtscriptDbView;
    const duck = {
      isView: true,
      isExternal: false,
      tableName: real.tableName,
      schema: undefined,
      viewPlan: real.viewPlan,
      fieldDescriptors: real.fieldDescriptors,
      getViewColumnMappings: () => real.getViewColumnMappings(),
      resolveFieldRef: (ref: any, qi?: any) => real.resolveFieldRef(ref, qi),
    };
    expect(duck instanceof AtscriptDbView).toBe(false);
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    adapter.registerReadable(duck as any);
    await adapter.ensureTable();
    const ddl = driver.calls.filter((c) => c.method === "exec").map((c) => c.sql);
    expect(ddl).toHaveLength(1);
    expect(ddl[0]).toMatch(/^CREATE (OR REPLACE )?VIEW/);
    expect(ddl[0]).not.toContain("computed");
    expect(ddl[0]).toContain('"label"');
  });
});

// ── Administrative adapter (no registered readable) ────────────────────────

// `DbSpace` runs the name-taking primitives (drop by name, inbound FKs) on a
// factory-fresh adapter that never had a readable registered. Everything —
// the schema included — must come from the connection (COALESCE(NULL, 'public'),
// the same default the bound path uses), never from `this._table`.
describe("PostgresAdapter — administrative adapter (no registered readable)", () => {
  it("hasRows / getObjectKind by name without a readable (schema → 'public')", async () => {
    const driver = createMockDriver({ getResult: { present: true, relkind: "v" } });
    const adapter = new PostgresAdapter(driver);
    expect(await adapter.hasRows("old_tokens")).toBe(true);
    expect(await adapter.getObjectKind("v")).toBe("view");
    expect(driver.calls[0].sql).toBe('SELECT EXISTS (SELECT 1 FROM "old_tokens") AS "present"');
    expect(driver.calls[1].sql).toContain("n.nspname = COALESCE($2, 'public')");
    expect(driver.calls[1].params).toEqual(["v", null]);
  });

  it("getReferencingForeignKeys / getExistingColumnsForTable without a readable pass a NULL schema", async () => {
    const fkDriver = createMockDriver({
      allResult: [
        {
          table_name: "children",
          constraint_name: "fk1",
          columns: ["parentId"],
          ref_columns: ["id"],
        },
      ],
    });
    expect(await new PostgresAdapter(fkDriver).getReferencingForeignKeys("parents")).toEqual([
      { table: "children", fields: ["parentId"], targetFields: ["id"] },
    ]);
    expect(fkDriver.calls[0].sql).toContain("rn.nspname = COALESCE($2, 'public')");
    expect(fkDriver.calls[0].params).toEqual(["parents", null]);

    const colDriver = createMockDriver({
      allResult: [
        {
          column_name: "id",
          data_type: "integer",
          udt_name: "int4",
          character_maximum_length: null,
          numeric_precision: 32,
          numeric_scale: 0,
          is_nullable: "NO",
          column_default: null,
          is_identity: "NO",
          formatted_type: "integer",
        },
      ],
    });
    const cols = await new PostgresAdapter(colDriver).getExistingColumnsForTable("parents");
    expect(cols.map((c) => [c.name, c.notnull, c.pk])).toEqual([["id", true, true]]);
    expect(colDriver.calls.map((c) => c.params)).toEqual([
      ["parents", null],
      ["parents", null],
    ]);
  });

  it("drops by name without a readable: unqualified, no CASCADE, a cycle in one statement", async () => {
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    await adapter.dropViewByName("v");
    await adapter.dropTableByName("parents");
    await adapter.dropTablesByName(["cycle_a", "cycle_b"]);
    expect(driver.calls.map((c) => c.sql)).toEqual([
      'DROP VIEW IF EXISTS "v"',
      'DROP TABLE IF EXISTS "parents"',
      'DROP TABLE IF EXISTS "cycle_a", "cycle_b"',
    ]);
  });

  it("DbSpace admin path: inbound FKs and drops of a removed table never touch a readable", async () => {
    const driver = createMockDriver({ allResult: [] });
    const space = new DbSpace(() => new PostgresAdapter(driver));
    space.getTable(fx.PfParent); // one bound adapter exists — the admin adapter is a different, unbound one
    expect(await space.getReferencingForeignKeys("gone_parents")).toEqual([]);
    await space.dropTablesByName(["gone_a", "gone_b"]);
    expect(driver.calls[0].params).toEqual(["gone_parents", null]);
    expect(driver.calls[1].sql).toBe('DROP TABLE IF EXISTS "gone_a", "gone_b"');
  });

  it("table-scoped operations on an unbound adapter fail with a clear error, not a TypeError", async () => {
    const adapter = new PostgresAdapter(createMockDriver());
    await expect(adapter.hasRows()).rejects.toThrow(/no registered readable/);
  });
});
