import { describe, it, expect, beforeAll } from "vite-plus/test";
import { AtscriptDbTable, AtscriptDbView, DbSpace } from "@atscript/db";
import type { TColumnDiff, TDbFieldMeta } from "@atscript/db";

import { PostgresAdapter, pgObjectName } from "../postgres-adapter";
import { prepareFixtures, createMockDriver } from "./test-utils";

let fx: Record<string, any>;
let CycleA: any;

function diff(partial: Partial<TColumnDiff>): TColumnDiff {
  return {
    added: [],
    removed: [],
    renamed: [],
    typeChanged: [],
    nullableChanged: [],
    defaultChanged: [],
    conflicts: [],
    ...partial,
  };
}

function pick(table: any, path: string): TDbFieldMeta {
  const f = table.fieldDescriptors.find((d: TDbFieldMeta) => d.path === path);
  if (!f) throw new Error(`no field ${path}`);
  return f;
}

beforeAll(async () => {
  await prepareFixtures();
  fx = await import("./fixtures/sync-preflight.as");
  CycleA = (await import("./fixtures/pf-cycle-a.as")).PfCycleA;
});

// Recorded-DDL coverage for the schema-sync primitives (since 0.1.128).
describe("PostgresAdapter — schema sync primitives", () => {
  it("rebuildPrimaryKey: DROP CONSTRAINT + ADD PRIMARY KEY in one statement", async () => {
    const driver = createMockDriver({ getResult: { conname: "pf_tokens_pkey" } });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfTokenV2, adapter);
    await adapter.rebuildPrimaryKey({ from: ["id"], to: ["code"] });
    const alter = driver.calls.filter((c) => c.method === "exec");
    expect(alter).toHaveLength(1);
    expect(alter[0].sql).toBe(
      'ALTER TABLE "pf_tokens" DROP CONSTRAINT "pf_tokens_pkey", ADD PRIMARY KEY ("code")',
    );
    expect(driver.calls[0].sql).toContain("contype = 'p'");
  });

  it("rebuildPrimaryKey: composite key, and a first key without DROP", async () => {
    const driver = createMockDriver({ getResult: null });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfTokenV2, adapter);
    await adapter.rebuildPrimaryKey({ from: [], to: ["code", "label"] });
    expect(driver.calls.find((c) => c.method === "exec")!.sql).toBe(
      'ALTER TABLE "pf_tokens" ADD PRIMARY KEY ("code", "label")',
    );
  });

  it("identity: a demoted increment column gets DROP IDENTITY, never DROP DEFAULT or increment()", async () => {
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    const table = new AtscriptDbTable(fx.PfTokenV2, adapter);
    await adapter.syncColumns(
      diff({ defaultChanged: [{ field: pick(table, "id"), oldDefault: "fn:increment" }] }),
    );
    const ddl = driver.calls.filter((c) => c.method === "exec").map((c) => c.sql);
    expect(ddl).toEqual(['ALTER TABLE "pf_tokens" ALTER COLUMN "id" DROP IDENTITY IF EXISTS']);
  });

  it("identity: gaining @db.default.increment emits ADD GENERATED (dropping a prior default first)", async () => {
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    const table = new AtscriptDbTable(fx.PfTokenV1, adapter);
    await adapter.syncColumns(
      diff({
        defaultChanged: [{ field: pick(table, "id"), oldDefault: "0", newDefault: "fn:increment" }],
      }),
    );
    const ddl = driver.calls.filter((c) => c.method === "exec").map((c) => c.sql);
    expect(ddl).toEqual([
      'ALTER TABLE "pf_tokens" ALTER COLUMN "id" DROP DEFAULT',
      'ALTER TABLE "pf_tokens" ALTER COLUMN "id" SET NOT NULL',
      'ALTER TABLE "pf_tokens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY',
    ]);
    expect(ddl.join("\n")).not.toContain("increment()");
  });

  it("identity → value default: DROP IDENTITY then SET DEFAULT", async () => {
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    const table = new AtscriptDbTable(fx.PfTokenV2, adapter);
    const id = {
      ...pick(table, "id"),
      defaultValue: { kind: "value", value: "7" },
    } as TDbFieldMeta;
    await adapter.syncColumns(
      diff({ defaultChanged: [{ field: id, oldDefault: "fn:increment", newDefault: "7" }] }),
    );
    expect(driver.calls.filter((c) => c.method === "exec").map((c) => c.sql)).toEqual([
      'ALTER TABLE "pf_tokens" ALTER COLUMN "id" DROP IDENTITY IF EXISTS',
      'ALTER TABLE "pf_tokens" ALTER COLUMN "id" SET DEFAULT 7',
    ]);
  });

  it("sync-owned drops never CASCADE; a cycle is one multi-table DROP", async () => {
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfParent, adapter);
    await adapter.dropTable();
    await adapter.dropTableByName("pf_children");
    await adapter.dropTablesByName(["pf_cycle_a", "pf_cycle_b"]);
    const ddl = driver.calls.filter((c) => c.method === "exec").map((c) => c.sql);
    expect(ddl).toEqual([
      'DROP TABLE IF EXISTS "pf_parents"',
      'DROP TABLE IF EXISTS "pf_children"',
      'DROP TABLE IF EXISTS "pf_cycle_a", "pf_cycle_b"',
    ]);
    expect(ddl.join("\n")).not.toContain("CASCADE");
  });

  it("hasRows uses SELECT EXISTS on the own or a named table", async () => {
    const driver = createMockDriver({ getResult: { present: true } });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfTokenV1, adapter);
    expect(await adapter.hasRows()).toBe(true);
    expect(driver.calls[0].sql).toBe('SELECT EXISTS (SELECT 1 FROM "pf_tokens") AS "present"');
    await adapter.hasRows("old_tokens");
    expect(driver.calls[1].sql).toBe('SELECT EXISTS (SELECT 1 FROM "old_tokens") AS "present"');
  });

  it("getReferencingForeignKeys queries pg_constraint by referenced relation", async () => {
    const driver = createMockDriver({
      allResult: [
        {
          table_name: "children",
          constraint_name: "fk1",
          columns: ["pa", "pb"],
          ref_columns: ["a", "b"],
        },
        { table_name: "logs", constraint_name: "fk2", columns: ["parentId"], ref_columns: ["id"] },
      ],
    });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfParent, adapter);
    expect(await adapter.getReferencingForeignKeys("pf_parents")).toEqual([
      { table: "children", fields: ["pa", "pb"], targetFields: ["a", "b"] },
      { table: "logs", fields: ["parentId"], targetFields: ["id"] },
    ]);
    const sql = driver.calls[0].sql;
    expect(sql).toContain("pg_constraint");
    expect(sql).toContain("c.contype = 'f'");
    expect(sql).toContain("confrelid");
    expect(driver.calls[0].params?.[0]).toBe("pf_parents");
  });

  it("getObjectKind maps pg_class.relkind", async () => {
    for (const [relkind, kind] of [
      ["r", "table"],
      ["p", "table"],
      ["v", "view"],
      ["m", "materialized"],
    ] as const) {
      const driver = createMockDriver({ getResult: { relkind } });
      const adapter = new PostgresAdapter(driver);
      new AtscriptDbTable(fx.PfParent, adapter);
      expect(await adapter.getObjectKind("x")).toBe(kind);
    }
    const driver = createMockDriver({ getResult: null });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfParent, adapter);
    expect(await adapter.getObjectKind("x")).toBeUndefined();
  });

  it("ensureTable omits inline FKs to deferred cycle members", async () => {
    const driver = createMockDriver();
    const space = new DbSpace(() => new PostgresAdapter(driver));
    const adapter = space.getAdapter(CycleA);
    await adapter.ensureTable({ deferForeignKeysTo: new Set(["pf_cycle_a", "pf_cycle_b"]) });
    expect(driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"))!.sql).not.toContain(
      "FOREIGN KEY",
    );
    driver.calls.length = 0;
    await adapter.ensureTable();
    expect(driver.calls.find((c) => c.sql.startsWith("CREATE TABLE"))!.sql).toContain(
      'FOREIGN KEY ("bId") REFERENCES "pf_cycle_b" ("id")',
    );
  });

  it("creates a view for a duck-typed readable (structural isView) and excludes @db.ignore fields", async () => {
    const real = new DbSpace(() => new PostgresAdapter(createMockDriver())).getView(
      fx.PfTokenList,
    ) as AtscriptDbView;
    const duck = {
      isView: true,
      isExternal: false,
      tableName: real.tableName,
      schema: undefined,
      viewPlan: real.viewPlan,
      fieldDescriptors: real.fieldDescriptors,
      getViewColumnMappings: () => real.getViewColumnMappings(),
      resolveFieldRef: (ref: any, qi?: any) => real.resolveFieldRef(ref, qi),
    };
    expect(duck instanceof AtscriptDbView).toBe(false);
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    adapter.registerReadable(duck as any);
    await adapter.ensureTable();
    const ddl = driver.calls.filter((c) => c.method === "exec").map((c) => c.sql);
    expect(ddl).toHaveLength(1);
    expect(ddl[0]).toMatch(/^CREATE (OR REPLACE )?VIEW/);
    expect(ddl[0]).not.toContain("computed");
    expect(ddl[0]).toContain('"label"');
  });
});

// ── Administrative adapter (no registered readable) ────────────────────────

// `DbSpace` runs the name-taking primitives (drop by name, inbound FKs) on a
// factory-fresh adapter that never had a readable registered. Everything —
// the schema included — must come from the connection (COALESCE(NULL, 'public'),
// the same default the bound path uses), never from `this._table`.
describe("PostgresAdapter — administrative adapter (no registered readable)", () => {
  it("hasRows / getObjectKind by name without a readable (schema → 'public')", async () => {
    const driver = createMockDriver({ getResult: { present: true, relkind: "v" } });
    const adapter = new PostgresAdapter(driver);
    expect(await adapter.hasRows("old_tokens")).toBe(true);
    expect(await adapter.getObjectKind("v")).toBe("view");
    expect(driver.calls[0].sql).toBe('SELECT EXISTS (SELECT 1 FROM "old_tokens") AS "present"');
    expect(driver.calls[1].sql).toContain("n.nspname = COALESCE($2, 'public')");
    expect(driver.calls[1].params).toEqual(["v", null]);
  });

  it("getReferencingForeignKeys / getExistingColumnsForTable without a readable pass a NULL schema", async () => {
    const fkDriver = createMockDriver({
      allResult: [
        {
          table_name: "children",
          constraint_name: "fk1",
          columns: ["parentId"],
          ref_columns: ["id"],
        },
      ],
    });
    expect(await new PostgresAdapter(fkDriver).getReferencingForeignKeys("parents")).toEqual([
      { table: "children", fields: ["parentId"], targetFields: ["id"] },
    ]);
    expect(fkDriver.calls[0].sql).toContain("rn.nspname = COALESCE($2, 'public')");
    expect(fkDriver.calls[0].params).toEqual(["parents", null]);

    const colDriver = createMockDriver({
      allResult: [
        {
          column_name: "id",
          data_type: "integer",
          udt_name: "int4",
          character_maximum_length: null,
          numeric_precision: 32,
          numeric_scale: 0,
          is_nullable: "NO",
          column_default: null,
          is_identity: "NO",
          formatted_type: "integer",
        },
      ],
    });
    const cols = await new PostgresAdapter(colDriver).getExistingColumnsForTable("parents");
    expect(cols.map((c) => [c.name, c.notnull, c.pk])).toEqual([["id", true, true]]);
    expect(colDriver.calls.map((c) => c.params)).toEqual([
      ["parents", null],
      ["parents", null],
    ]);
  });

  it("drops by name without a readable: unqualified, no CASCADE, a cycle in one statement", async () => {
    const driver = createMockDriver();
    const adapter = new PostgresAdapter(driver);
    await adapter.dropViewByName("v");
    await adapter.dropTableByName("parents");
    await adapter.dropTablesByName(["cycle_a", "cycle_b"]);
    expect(driver.calls.map((c) => c.sql)).toEqual([
      'DROP VIEW IF EXISTS "v"',
      'DROP TABLE IF EXISTS "parents"',
      'DROP TABLE IF EXISTS "cycle_a", "cycle_b"',
    ]);
  });

  it("DbSpace admin path: inbound FKs and drops of a removed table never touch a readable", async () => {
    const driver = createMockDriver({ allResult: [] });
    const space = new DbSpace(() => new PostgresAdapter(driver));
    space.getTable(fx.PfParent); // one bound adapter exists — the admin adapter is a different, unbound one
    expect(await space.getReferencingForeignKeys("gone_parents")).toEqual([]);
    await space.dropTablesByName(["gone_a", "gone_b"]);
    expect(driver.calls[0].params).toEqual(["gone_parents", null]);
    expect(driver.calls[1].sql).toBe('DROP TABLE IF EXISTS "gone_a", "gone_b"');
  });

  it("table-scoped operations on an unbound adapter fail with a clear error, not a TypeError", async () => {
    const adapter = new PostgresAdapter(createMockDriver());
    await expect(adapter.hasRows()).rejects.toThrow(/no registered readable/);
  });
});

// ── recreateTable (0.1.129): no CASCADE, inbound FKs restored by name, own constraints renamed ──

/** One inbound-FK row as `recreateTable`'s capture query returns it. */
function fkRow(
  constraint: string,
  table: string,
  col: string,
  refCol: string,
  rules: { del?: string; upd?: string } = {},
) {
  return {
    constraint_name: constraint,
    table_name: table,
    table_schema: "public",
    column_name: col,
    ref_column_name: refCol,
    delete_rule: rules.del ?? "NO ACTION",
    update_rule: rules.upd ?? "NO ACTION",
  };
}

/** A constraint row of the recreated table as `_renameTempConstraints` reads it. */
type TConRow = { conname: string; contype: string; columns: string[] | null };

/** A driver that answers the capture, column and constraint queries of a recreate. */
function recreateDriver(opts: {
  table: string;
  inbound: ReturnType<typeof fkRow>[];
  /** Constraints on the table after the RENAME, given the temp name PostgreSQL named them for. */
  constraints?: (tmp: string) => TConRow[];
  /** Relation names present in the schema (the `pg_class` check before a PK/UNIQUE rename). */
  relations?: string[];
  execError?: (sql: string) => Error | undefined;
}) {
  let tmp = "";
  const driver = createMockDriver({
    allResult: (sql, params) => {
      if (sql.includes("referential_constraints")) {
        return opts.inbound;
      }
      if (sql.includes("information_schema.columns")) {
        return [{ column_name: "id" }, { column_name: "code" }, { column_name: "label" }];
      }
      if (sql.includes("pg_constraint")) {
        return (
          opts.constraints ??
          ((t) => [{ conname: pgObjectName(t, [], "pkey"), contype: "p", columns: ["id"] }])
        )(tmp);
      }
      throw new Error(`unexpected all(): ${sql} ${JSON.stringify(params)}`);
    },
    getResult: (sql: string, params?: unknown[]) =>
      sql.includes("pg_class") && (opts.relations ?? []).includes(params![0] as string)
        ? { present: true }
        : null,
    execError: (sql) => {
      const m = new RegExp(`CREATE TABLE IF NOT EXISTS "(${opts.table}__tmp_\\d+)"`).exec(sql);
      if (m) {
        tmp = m[1];
      }
      return opts.execError?.(sql);
    },
  });
  return { driver, execs: () => driver.calls.filter((c) => c.method === "exec").map((c) => c.sql) };
}

describe("PostgresAdapter — recreateTable", () => {
  let Rn: Record<string, any>;
  beforeAll(async () => {
    Rn = await import("./fixtures/recreate-names.as");
  });

  it("drops without CASCADE and restores inbound FKs under their captured names (one statement per constraint)", async () => {
    const { driver, execs } = recreateDriver({
      table: "pf_tokens",
      inbound: [
        // A two-column FK is one constraint, columns in ordinal order
        fkRow("children_pa_pb_fkey", "children", "pa", "id", { del: "CASCADE" }),
        fkRow("children_pa_pb_fkey", "children", "pb", "code", { del: "CASCADE" }),
        fkRow("logs_token_fkey", "logs", "tokenId", "id", { upd: "SET NULL" }),
      ],
    });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfTokenV1, adapter);
    await adapter.recreateTable();

    const sql = execs();
    expect(sql).toContain('DROP TABLE IF EXISTS "pf_tokens"');
    expect(sql.some((s) => s.startsWith("DROP TABLE") && s.includes("CASCADE"))).toBe(false);
    expect(sql).toContain(
      'ALTER TABLE "public"."children" DROP CONSTRAINT IF EXISTS "children_pa_pb_fkey"',
    );
    expect(sql).toContain(
      'ALTER TABLE "public"."logs" DROP CONSTRAINT IF EXISTS "logs_token_fkey"',
    );
    expect(sql).toContain(
      'ALTER TABLE "public"."children" ADD CONSTRAINT "children_pa_pb_fkey" FOREIGN KEY ("pa", "pb") REFERENCES "pf_tokens" ("id", "code") ON DELETE CASCADE',
    );
    expect(sql).toContain(
      'ALTER TABLE "public"."logs" ADD CONSTRAINT "logs_token_fkey" FOREIGN KEY ("tokenId") REFERENCES "pf_tokens" ("id") ON UPDATE SET NULL',
    );
    expect(sql.filter((s) => s.includes("ADD CONSTRAINT"))).toHaveLength(2);
    expect(sql.filter((s) => /^(BEGIN|COMMIT|ROLLBACK)$/.test(s))).toEqual(["BEGIN", "COMMIT"]);
    // The capture query includes FKs to UNIQUE targets, pairs the referenced
    // column by its position in the referenced key, ordinal-ordered
    const capture = driver.calls.find((c) => c.sql.includes("referential_constraints"))!;
    expect(capture.sql).toContain("constraint_type IN ('PRIMARY KEY', 'UNIQUE')");
    expect(capture.sql).toContain("kcur.ordinal_position = kcu.position_in_unique_constraint");
    expect(capture.sql).toContain(
      "ORDER BY tc.table_schema, tc.table_name, tc.constraint_name, kcu.ordinal_position",
    );
    expect(capture.params).toEqual([null, "pf_tokens"]);
  });

  it("a self-referencing FK is neither dropped nor restored; the temp CREATE omits it (syncForeignKeys re-adds it)", async () => {
    const { driver, execs } = recreateDriver({
      table: "rn_folders",
      inbound: [
        fkRow("rn_folders_parentId_fkey", "rn_folders", "parentId", "id"),
        fkRow(
          "rn_long_folderId_fkey",
          "rn_a_long_table_name_past_the_pg_limit_x_1234",
          "folderId",
          "id",
        ),
      ],
    });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(Rn.RnFolder, adapter);
    await adapter.recreateTable();

    const sql = execs();
    expect(sql.filter((s) => s.includes("DROP CONSTRAINT"))).toEqual([
      'ALTER TABLE "public"."rn_a_long_table_name_past_the_pg_limit_x_1234" DROP CONSTRAINT IF EXISTS "rn_long_folderId_fkey"',
    ]);
    expect(sql.filter((s) => s.includes("ADD CONSTRAINT"))).toEqual([
      'ALTER TABLE "public"."rn_a_long_table_name_past_the_pg_limit_x_1234" ADD CONSTRAINT "rn_long_folderId_fkey" FOREIGN KEY ("folderId") REFERENCES "rn_folders" ("id")',
    ]);
    const create = sql.find((s) => s.startsWith("CREATE TABLE IF NOT EXISTS"))!;
    expect(create).not.toContain("REFERENCES");
  });

  it("renames the recreated table's constraints to the final names and skips a taken name", async () => {
    const { driver, execs } = recreateDriver({
      table: "pf_tokens",
      inbound: [],
      constraints: (tmp) => [
        { conname: `${tmp}_pkey`, contype: "p", columns: ["id"] },
        { conname: `${tmp}_ownerId_fkey`, contype: "f", columns: ["ownerId"] },
        { conname: `${tmp}_code_key`, contype: "u", columns: ["code"] },
        // Not PostgreSQL's name for the temp table → left alone
        { conname: "pf_tokens_code_key", contype: "u", columns: ["code"] },
        { conname: "tokens_label_check", contype: "c", columns: ["label"] },
      ],
      // `pf_tokens_code_key` is an index in the schema too — the UNIQUE rename must not collide
      relations: ["pf_tokens_code_key"],
    });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfTokenV1, adapter);
    await adapter.recreateTable();

    const sql = execs();
    const create = sql.find((s) => s.startsWith("CREATE TABLE IF NOT EXISTS"))!;
    const tmp = /"(pf_tokens__tmp_\d+)"/.exec(create)![1];
    const renames = sql.filter((s) => s.includes("RENAME CONSTRAINT"));
    // `<tmp>_code_key` → `pf_tokens_code_key` is skipped (taken); the check constraint is not auto-named
    expect(renames).toEqual([
      `ALTER TABLE "pf_tokens" RENAME CONSTRAINT "${tmp}_pkey" TO "pf_tokens_pkey"`,
      `ALTER TABLE "pf_tokens" RENAME CONSTRAINT "${tmp}_ownerId_fkey" TO "pf_tokens_ownerId_fkey"`,
    ]);
    // Renames run after the RENAME TO and before COMMIT
    const renameTo = sql.findIndex((s) => s.includes(`RENAME TO "pf_tokens"`));
    expect(sql.indexOf(renames[0])).toBeGreaterThan(renameTo);
    expect(sql.indexOf(renames[1])).toBeLessThan(sql.indexOf("COMMIT"));
    // The constraint query targets the renamed table; the PK/UNIQUE targets were checked in pg_class
    const query = driver.calls.find((c) => c.method === "all" && c.sql.includes("pg_constraint"))!;
    expect(query.params).toEqual(["pf_tokens", null]);
    const checks = driver.calls.filter((c) => c.method === "get" && c.sql.includes("pg_class"));
    expect(checks.map((c) => c.params![0])).toEqual(["pf_tokens_pkey", "pf_tokens_code_key"]);
  });

  it("recognises and renames the constraints of a table whose auto-names PostgreSQL truncated", async () => {
    const long = "rn_a_long_table_name_past_the_pg_limit_x_1234";
    const { driver, execs } = recreateDriver({
      table: long,
      inbound: [],
      constraints: (tmp) => [
        { conname: pgObjectName(tmp, [], "pkey"), contype: "p", columns: ["id"] },
        { conname: pgObjectName(tmp, ["folderId"], "fkey"), contype: "f", columns: ["folderId"] },
        { conname: pgObjectName(tmp, ["code"], "not_null"), contype: "n", columns: ["code"] },
      ],
    });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(Rn.RnLongName, adapter);
    await adapter.recreateTable();

    const sql = execs();
    const tmp = new RegExp(`"(${long}__tmp_\\d+)"`).exec(
      sql.find((s) => s.startsWith("CREATE TABLE IF NOT EXISTS"))!,
    )![1];
    // The temp-table names exceed 63 bytes before PostgreSQL truncates them,
    // so a `<tmp>` prefix match would miss them
    expect(`${tmp}_pkey`.length).toBeGreaterThan(63);
    const expected = [
      [pgObjectName(tmp, [], "pkey"), `${long}_pkey`],
      [pgObjectName(tmp, ["folderId"], "fkey"), `${long}_folderId_fkey`],
      [pgObjectName(tmp, ["code"], "not_null"), `${long}_code_not_null`],
    ];
    for (const [from, to] of expected) {
      expect(from.length).toBeLessThanOrEqual(63);
      expect(from.startsWith(tmp)).toBe(false);
      expect(from).not.toBe(to);
    }
    expect(sql.filter((s) => s.includes("RENAME CONSTRAINT"))).toEqual(
      expected.map(([from, to]) => `ALTER TABLE "${long}" RENAME CONSTRAINT "${from}" TO "${to}"`),
    );
  });

  it("a refused DROP (2BP01) rolls back and rethrows the same error with PostgreSQL's detail appended", async () => {
    const boom = Object.assign(
      new Error("cannot drop table pf_tokens because other objects depend on it"),
      { code: "2BP01", detail: "view token_report depends on table pf_tokens" },
    );
    const { driver, execs } = recreateDriver({
      table: "pf_tokens",
      inbound: [fkRow("logs_token_fkey", "logs", "tokenId", "id")],
      execError: (sql) => (sql.startsWith("DROP TABLE") ? boom : undefined),
    });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfTokenV1, adapter);
    await expect(adapter.recreateTable()).rejects.toBe(boom);
    expect(boom.message).toBe(
      "cannot drop table pf_tokens because other objects depend on it — view token_report depends on table pf_tokens",
    );
    expect(boom.code).toBe("2BP01");
    const sql = execs();
    expect(sql.filter((s) => /^(BEGIN|COMMIT|ROLLBACK)$/.test(s))).toEqual(["BEGIN", "ROLLBACK"]);
    expect(sql.some((s) => s.includes("ADD CONSTRAINT"))).toBe(false);
    // Nothing ran on the pool after the rollback (no sequence reset)
    expect(driver.calls.filter((c) => c.method === "run")).toEqual([]);
  });

  it("an error without detail is rethrown as-is", async () => {
    const boom = new Error("boom");
    const { driver } = recreateDriver({
      table: "pf_tokens",
      inbound: [],
      execError: (sql) => (sql.startsWith("DROP TABLE") ? boom : undefined),
    });
    const adapter = new PostgresAdapter(driver);
    new AtscriptDbTable(fx.PfTokenV1, adapter);
    await expect(adapter.recreateTable()).rejects.toBe(boom);
    expect(boom.message).toBe("boom");
  });
});

describe("pgObjectName", () => {
  it("joins table, columns and label; shortens the longer part first to fit 63 bytes", () => {
    expect(pgObjectName("users", [], "pkey")).toBe("users_pkey");
    expect(pgObjectName("users", ["a", "b"], "fkey")).toBe("users_a_b_fkey");
    const long = "t".repeat(70);
    expect(pgObjectName(long, [], "pkey")).toBe(`${"t".repeat(58)}_pkey`);
    const name = pgObjectName(long, ["c".repeat(30)], "key");
    expect(name.length).toBe(63);
    expect(name).toBe(`${"t".repeat(29)}_${"c".repeat(29)}_key`);
  });
});
