import path from "node:path";
import { fileURLToPath } from "node:url";

import type { AtscriptRepo, SemanticNode, TOutput } from "@atscript/core";
import { DEFAULT_FORMAT } from "@atscript/core";

import { getAnnotationAlias } from "../shared/annotation-utils";
import { DEFAULT_DB_SPACE } from "../shared/consts";

/** Options for the generated model manifest (see {@link dbPlugin}). */
export interface TDbManifestOptions {
  /** Output path for the generated module, relative to the project root. */
  path: string;
}

const DB_ENTITY_ANNOTATIONS = ["db.table", "db.view", "db.view.for"];

function isDbEntity(node: SemanticNode): boolean {
  return DB_ENTITY_ANNOTATIONS.some((name) => node.countAnnotations(name) > 0);
}

interface TManifestEntry {
  /** Import alias used in the manifest (deduplicated across files). */
  alias: string;
  /** Exported name in the source document. */
  exportName: string;
  /** Manifest-relative import specifier (keeps the `.as` extension). */
  specifier: string;
  isView: boolean;
  space: string;
}

/**
 * Renders the model-manifest module: an inventory of every exported
 * `@db.table` / `@db.view` entity in the project, grouped by `@db.space`.
 *
 * The manifest is an inventory, NOT an action — consumers pass it (filtered,
 * extended with external-package models, split per space) to `syncSchema` /
 * `assertExposed` themselves.
 *
 * Runs on full builds for the `dts` / default formats (the same gate as
 * `atscript.d.ts`), so narrowed special-purpose builds (e.g. the `asc db sync`
 * temp compile) never shrink a committed manifest.
 */
export async function generateModelManifest(
  options: TDbManifestOptions,
  output: TOutput[],
  format: string,
  repo: AtscriptRepo,
): Promise<void> {
  if (format !== "dts" && format !== DEFAULT_FORMAT) {
    return;
  }

  const manifestTarget = path.isAbsolute(options.path)
    ? options.path
    : path.join(repo.root, options.path);
  const manifestDir = path.dirname(manifestTarget);

  // Unique source documents, discovered from this build's outputs.
  const sources = [...new Set(output.map((o) => o.source).filter(Boolean))].toSorted();

  const docs = await Promise.all(sources.map((source) => repo.openDocument(source)));

  const entries: TManifestEntry[] = [];
  const usedAliases = new Set<string>();
  for (const [i, doc] of docs.entries()) {
    if (!doc) continue;
    const source = sources[i];
    const docPath = source.startsWith("file://") ? fileURLToPath(source) : source;
    // Skip the manifest itself and anything outside the project root.
    if (docPath === manifestTarget) continue;

    let specifier = path.relative(manifestDir, docPath).split(path.sep).join("/");
    if (!specifier.startsWith(".")) specifier = `./${specifier}`;

    for (const [exportName, node] of [...doc.exports.entries()].toSorted(([a], [b]) =>
      a.localeCompare(b),
    )) {
      if (!isDbEntity(node)) continue;
      let alias = exportName;
      for (let n = 1; usedAliases.has(alias); n++) {
        alias = `${exportName}_${n}`;
      }
      usedAliases.add(alias);
      entries.push({
        alias,
        exportName,
        specifier,
        isView: node.countAnnotations("db.view") > 0 || node.countAnnotations("db.view.for") > 0,
        space: getAnnotationAlias(node, "db.space") || DEFAULT_DB_SPACE,
      });
    }
  }

  const imports = entries.map((e) =>
    e.alias === e.exportName
      ? `import { ${e.exportName} } from "${e.specifier}"`
      : `import { ${e.exportName} as ${e.alias} } from "${e.specifier}"`,
  );

  const tables = entries.filter((e) => !e.isView).map((e) => e.alias);
  const views = entries.filter((e) => e.isView).map((e) => e.alias);

  const spaces = new Map<string, string[]>();
  for (const e of entries) {
    const group = spaces.get(e.space) ?? [];
    group.push(e.alias);
    spaces.set(e.space, group);
  }
  const spaceKeys = [...spaces.keys()].toSorted((a, b) =>
    a === DEFAULT_DB_SPACE ? -1 : b === DEFAULT_DB_SPACE ? 1 : a.localeCompare(b),
  );

  const list = (items: string[]) => (items.length ? `[${items.join(", ")}] as const` : "[]");

  const content = [
    "/* oxlint-disable */",
    "/* eslint-disable */",
    "/**",
    " * 🪄 This file was generated by Atscript (@atscript/db model manifest)",
    " * Do not edit this file!",
    " *",
    " * Re-generate with `npx asc -f dts`.",
    " */",
    ...imports,
    "",
    `export const dbTables = ${list(tables)}`,
    `export const dbViews = ${list(views)}`,
    "/** Every @db.table / @db.view model in this project. */",
    `export const atscriptModels = ${list(entries.map((e) => e.alias))}`,
    '/** Models grouped by @db.space (absent annotation → "default"). */',
    "export const modelsBySpace = {",
    ...spaceKeys.map((key) => `  ${JSON.stringify(key)}: ${list(spaces.get(key)!)},`),
    "} as const",
    "",
  ].join("\n");

  output.push({
    fileName: path.basename(manifestTarget),
    content,
    source: "",
    target: manifestTarget,
  });
}
